on:
  - pull_request
  - push
  - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build setup-watcom
        run: |
          ./build.sh
          mv packed/index.js index.js
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: action-artifact
          if-no-files-found: error
          path: |
            index.js

  test:
    name: "OpenWatcom ${{ matrix.version }} on ${{ matrix.runner }}"
    needs: build
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest
        version:
          - "1.8"
          - "1.9"
          - "2.0"
          - "2.0-64"
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: action-artifact
      - name: "Run action"
        run: |
          node index.js
        env:
          INPUT_VERSION: "${{ matrix.version }}"
          INPUT_TAG: ""
          INPUT_LOCATION: ""
          INPUT_ENVIRONMENT: "true"
      - name: Use watcom
        run: |
          wcl -h
          wcl386 -h

  release:
    name: "Create release"
    needs: test
    runs-on: "ubuntu-latest"
    if: ${{ (github.repository == 'open-watcom/setup-watcom') && (github.ref_name == 'master') }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure user
        run: |
          git config --global user.name 'Open Watcom'
          git config --global user.email '2045606+open-watcom@users.noreply.github.com'
      - name: Build setup-watcom
        run: |
          ./build.sh
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Create release
        run: |
          ./release.py v0
